### ISSUE TITLE
[eslint] Unexpected use of 'self'

### ISSUE THREAD

**Issue by dparkar** [scottdomes/pwa-experiment#1]
I am using visual studio code and the eslint plugin. It shows an error on "self" variable in service-worker.js: 

> [eslint] Unexpected use of 'self'. (no-restricted-globals)
> var self: Window
> 

When I do "npm start" and look at the chrome dev tools is doesn't say anything after : 
"ServiceWorker registration successful with scope:  http://localhost:3000/"

As per your blog it is suppose to say that the cache are being deleted : 
"Delete caches"
"All caches are deleted"

**Comment by scottdomes** [comment]
You can disable the Eslint alert for self by adding /* global self */ to the top of service-worker.js.

Also make sure that doCache is set to true in the same file. I disabled it in this repo because it complicates the development process.

**Comment by dparkar** [comment]
I see what you mean, read the docs [here](http://eslint.org/docs/user-guide/configuring#specifying-globals).

However, adding `/* global self */` on top doesn't change anything. But adding `var self = this;` or using `this.addEventListener(...)` seems to do avoid it.

I cloned this repo, ran "npm install" and then "npm start". Then I opened the dev tools on chrome. I didn't see the "Delete caches" and "All caches are deleted" logs. May be the picture displaying the console is of another run where logging was added ? That's what is confusing.

Appreciate the help.  I am just getting started with React and PWAs.

**Comment by dparkar** [comment]
Another observation. [Asked on SO](https://stackoverflow.com/questions/45559784/react-pwa-create-react-app-and-chromes-lighthouse-extension).

**Comment by scottdomes** [comment]
Add `var self = this;` or any alternative doesn't technically avoid the problem either, it just tricks ESLint. Declaring that self is a global at the top of the file is the most readable way to solve it, or you could add `self` to the list of "safe" globals in your .eslintrc. 

As for the create-react-app question: the makers of CRA advertised the newest version as "every app is now a PWA!" Technically, they really only added a service worker and some barebones functionality. Which is great (and CRA is a phenomenal tool), but misleading in that PWAs require a major focus on performance to support all network connections... which can only be achieved via developer effort, beyond the scope of what CRA can do.

All that said, in your specific SO answer, your screenshot of Lighthouse shows a lack of service worker registration, which definitely should be occurring in newer versions of CRA. Keep in mind CRA only turns on the sw-precache-plugin for production builds, so if you're running Lighthouse on a development build, it won't work.

**Comment by dparkar** [comment]
You're right, I commented out the check for `process.env.NODE_ENV === 'production'` and now Lighthouse audit for service worker registration is checked off.

If you would like to reply to SO question, please feel free to do so and I can mark it as answered.
